id: P004373
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18706
  title: གྲོང་གསེབ་ཀྱི་དམངས་དོན་སྐོར་གྱི་རྩོད་གཞི།
  author: ''
  volumes:
    21bf16bc8ba3451e82fbe1f00f44eac1:
      image_group_id: I8LS18708
      title: ''
      volume_number: 1
      total_pages: 247
      base_file: v001.txt
